name: SimpleFortuneCookies

services:
  frontend:
    container_name: frontend_container
    depends_on:
      - backend
    image: magnusthomsen/sfc_frontend:latest
#    build:
#      context: .
#      dockerfile: Dockerfile_frontend
    environment:
      - BACKEND_DNS=backend_container
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
  backend:
    depends_on:
      - redis
    container_name: backend_container
    image: magnusthomsen/sfc_backend:latest
#    build:
#      context: .
#      dockerfile: Dockerfile_backend
    environment:
      - REDIS_DNS=redis_container
    ports:
      - "9000:9000"

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"