apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-deployment
spec:
  selector:
    app: backend-deployment
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
