apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-deployment
spec:
  selector:
    app: frontend-deployment
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080