apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      volumes:
        - name: redis-pvc
          persistentVolumeClaim:
            claimName: redis-pvc
      containers:
        - name: redis-container
          image: redis:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 6379
          volumeMounts:
            - name: redis-pvc
              mountPath: "/mnt/data/redis"
