name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone down repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build frontend
      run: |
        cd ./frontend 
        go build frontend
    - name: Build backend
      run: |
        cd ./backend
        go build backend
    - name: Test frontend
      run: |
        cd ./frontend
        go test frontend
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_frontend
          push: true
          tags: magnusthomsen/sfc_frontend:latest
          cache-from: type=registry,ref=magnusthomsen/sfc_frontend:latest
          cache-to: type=inline

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_backend
          push: true
          tags: magnusthomsen/sfc_backend:latest
          cache-from: type=registry,ref=magnusthomsen/sfc_backend:latest
          cache-to: type=inline
  deploy:
    runs-on: ubuntu-latest
    needs: [publish_images]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
      - run: kubectl --kubeconfig kubeconfig apply -f ./kubernetes_config
  test-availability:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Docker Compose with Tests
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: ./compose.yaml
          up-flags: "--build"
          down-flags: "--volumes"
          test-container: "frontend_container" # must match container name in docker-compose.yml
          test-command: "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/healthz"
          annotate: "false"