# Maintain mainline integrity, PRs against main needs to be tested by CI before merging. 
name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone down repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Build frontend
      run: |
        cd ./frontend 
        go build frontend
    - name: Build backend
      run: |
        cd ./backend
        go build backend
    - name: Test frontend
      run: |
        cd ./frontend
        go test frontend
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend image
        run: docker build -t magnusthomsen/sfc_frontend:latest -f Dockerfile_frontend .
      - name: Build backend image
        run: docker build -t magnusthomsen/sfc_backend:latest -f Dockerfile_backend .
      - name: Push to Docker Hub
        run: |
          docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push magnusthomsen/sfc_frontend:latest
          docker push magnusthomsen/sfc_backend:latest